### ISSUE TITLE
Trouble installing and using

### ISSUE THREAD

**Issue by mpaya** [biocore-ntnu/epic2#5]
Hi,
Thanks for preparing the tool. I wanted to give it a try but I'm finding issues to install and use it. I'm working on a Linux Mint Tara system and have installed both anaconda2 and anaconda3, and find the same issues with both python versions. 
* When trying to install using `pip install epic2`, I get the following:
```
...
    running build_ext
    building 'epic2.src.reads_to_bins' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/epic2
    creating build/temp.linux-x86_64-3.6/epic2/src
    gcc -pthread -B /home/bioinfo5/software/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bioinfo5/software/anaconda3/include/ -I. -I/home/bioinfo5/software/anaconda3/include/python3.6m -c epic2/src/reads_to_bins.cpp -o build/temp.linux-x86_64-3.6/epic2/src/reads_to_bins.o -Ofast -Wall -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    epic2/src/reads_to_bins.cpp:664:10: fatal error: read_files.hpp: No such file or directory
     #include "read_files.hpp"
              ^~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/bioinfo5/software/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-v6bpdckg/epic2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-y43lh7i2/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-v6bpdckg/epic2/
```

* Using `git clone` and `python install`, there is no error. But when I try to run the example, or even display the usage typing `epic2`, I get this message:
```
$ epic2
Traceback (most recent call last):
  File "/home/bioinfo5/software/anaconda3/bin/epic2", line 4, in <module>
    __import__('pkg_resources').run_script('epic2==0.0.2', 'epic2')
  File "/home/bioinfo5/software/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bioinfo5/software/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/home/bioinfo5/software/anaconda3/lib/python3.6/site-packages/epic2-0.0.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/epic2", line 19, in <module>
    from epic.version import __version__
ModuleNotFoundError: No module named 'epic'
```
Any ideas on how could I get properly installed and running? Thanks

**Comment by endrebak** [comment]
Thanks for bothering to report this. I'll start looking into it. This is my first library written from scratch that uses C++ extensively, so I have a bit of learning to do when it comes to writing the setup-files :)

We are preparing this for submission, so I'll try to find the error quickly :)

**Comment by endrebak** [comment]
Try `pip install epic2 --no-cache-dir` and tell me what messages you get now please :)

**Comment by mpaya** [comment]
With that command, installation shows no errors and epic2 gets installed. Trying to run it does though. I'm still not sure whether it should be used with python 2 or 3, so I tried with both.
```
$ epic2 -t examples/test.bed -c examples/control.bed > results.txt
Traceback (most recent call last):
  File "/home/bioinfo5/software/anaconda3/bin/epic2", line 19, in <module>
    from epic.version import __version__
ModuleNotFoundError: No module named 'epic'

### or...
Traceback (most recent call last):
  File "/home/bioinfo5/software/anaconda2/bin/epic2", line 19, in <module>
    from epic.version import __version__
ImportError: No module named epic.version
```

**Comment by mpaya** [comment]
I was thinking something about that, makes sense that it works for you if you already had epic installed. have a good weekend :)

**Comment by endrebak** [comment]
I have made several fixes. Does `pip install epic2==0.0.11`work? :)

**Comment by mpaya** [comment]
It does, so does the latest version with `pip install epic2` (`Successfully installed epic2-0.0.12`). Please let me know when the error about the epic module not being found gets fixed. :)

**Comment by endrebak** [comment]
That is weird - it is fixed. Could you try `pip uninstall epic2` (possibly multiple times, until it says it can't find the module) and then try reinstalling `pip install epic2 --no-cache-dir`?

**Comment by endrebak** [comment]
I found another misplaced reference to epic. Could you please try `pip install epic2==0.0.13` and see if it works now please?

**Comment by mpaya** [comment]
Hi. I always uninstall if it doesn't work. Sorry to say that I'm still getting the same error messages, either with the latest version and no-cache option. 
```
Traceback (most recent call last):
  File "/home/bioinfo5/software/anaconda2/bin/epic2", line 19, in <module>
    from epic.version import __version__
ImportError: No module named epic.version
```

**Comment by endrebak** [comment]
Now `0.0.14` is out which finally should fix this :)

**Comment by mpaya** [comment]
It works!! ^^
